# Generated by Django 2.1.2 on 2018-11-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioadopcion',
            name='region',
            field=models.CharField(choices=[('Tarapaca', 'Tarapaca'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaiso', 'Valparaiso'), ('O´Higgins', 'O´Higgins'), ('Maule', 'Maule'), ('Concepcion', 'Concepcion'), ('Araucania', 'Araucania'), ('Los Lagos', 'Los Lagos'), ('Aysén', 'Aysén'), ('Magallanes', 'Magallanes'), ('Metropolitana', 'Metropolitana'), ('Los Rios', 'Los Rios'), ('Arica', 'Arica'), ('Ñuble', 'Ñuble')], help_text='region', max_length=60),
        ),
    ]
