# Generated by Django 2.1.2 on 2018-11-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_auto_20181105_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioadopcion',
            name='ciudad',
            field=models.CharField(choices=[('Iquique', 'Iquique'), ('Antofagasta', 'Antofagasta'), ('Copiapo', 'Copiapo'), ('Coquimbo', 'Coquimbo'), ('Valparaiso', 'Valparaiso'), ('Rancagua', 'Rancagua'), ('Talca', 'Talca'), ('Concepcion', 'Concepcion'), ('Temuco', 'Temuco'), ('Puerto Montt', 'Puerto Montt'), ('Coyhiaique', 'Coyhiaique'), ('Punta Arenas', 'Punta Arenas'), ('Santiago', 'Santiago'), ('Valdivia', 'Valdivia'), ('Arica', 'Arica'), ('Chillán', 'Chillán')], help_text='ciudad', max_length=60),
        ),
        migrations.AlterField(
            model_name='formularioadopcion',
            name='tipoVivienda',
            field=models.CharField(choices=[('Casa patio grande', 'Casa patio grande'), ('Casa patio pequeño', 'Casa patio pequeño'), ('Casa sin patio', 'Casa sin patio'), ('Departamento', 'Departamento')], help_text='vivienda', max_length=60),
        ),
    ]
