# Generated by Django 2.1.2 on 2018-11-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_auto_20181106_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioRescatado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('nombre', models.CharField(max_length=50)),
                ('razaPredominante', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Rescatado', 'Rescatado'), ('Disponible', 'Disponible'), ('Adoptado', 'Adoptado')], help_text='Estado', max_length=50)),
            ],
        ),
    ]
